# Generated by Django 5.1.6 on 2025-02-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_cover_photo_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='default/cover_default.jpg', null=True, upload_to='cover_photos/'),
        ),
    ]
