# Generated by Django 5.1.6 on 2025-02-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='default/cover_default.jpg', upload_to='cover_photos/'),
        ),
    ]
