# Generated by Django 5.1.6 on 2025-03-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_alter_friendship_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted')], default='requested', max_length=10),
        ),
    ]
