# Generated by Django 5.1.6 on 2025-03-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0003_alter_friendship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('sent', 'sent')], default='requested', max_length=10),
        ),
    ]
