# Generated by Django 5.1.6 on 2025-03-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('posts', '0004_alter_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='media_files',
            field=models.ManyToManyField(blank=True, to='media_library.mediafile'),
        ),
    ]
