# Generated by Django 5.1.6 on 2025-03-20 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_alter_mediafile_file'),
        ('posts', '0005_remove_post_image_post_media_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media_files',
        ),
        migrations.AddField(
            model_name='post',
            name='media_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='media_library.mediafile'),
        ),
    ]
