# Generated by Django 5.1.6 on 2025-03-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_alter_mediafile_file'),
        ('posts', '0007_remove_post_media_files_post_media_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_files',
            field=models.ManyToManyField(blank=True, to='media_library.mediafile'),
        ),
    ]
